import { useState, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { cn } from "@/lib/utils";
import {
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Clock,
  FileText,
  Lock,
  Eye,
  ChevronDown,
  ChevronUp,
  Fingerprint,
} from "lucide-react";

/* ─────────────────────────────────────────────────────────────
   1. PDF DISCLAIMER TEXT (reusable constant)
   ───────────────────────────────────────────────────────────── */
export const LEGAL_DISCLAIMER_HE =
  'דו"ח זה הופק באמצעות מערכת האנליזה של חיתומית המבוססת על נתוני אמת שהוזנו. ' +
  'האחריות על אמיתות הנתונים חלה על הלקוח. הדו"ח מהווה אינדיקציה חיתומית טכנולוגית ' +
  'ואינו מהווה אישור סופי של הבנק, אך מבוסס על מדיניות האשראי המעודכנת.';

export const LEGAL_DISCLAIMER_EN =
  "This report was generated by Chitumit AI analysis engine based on user-submitted data. " +
  "Responsibility for data accuracy lies with the client. This report constitutes a technological " +
  "underwriting indication and does not represent a final bank approval.";

/* ─────────────────────────────────────────────────────────────
   2. COMPLIANCE GUARDRAIL — checks LTV & DTI before export
   ───────────────────────────────────────────────────────────── */
interface ComplianceCheckResult {
  passed: boolean;
  warnings: { code: string; label: string; value: string; limit: string; severity: "error" | "warning" }[];
}

export function runComplianceCheck(lead: {
  mortgage_amount: number | null;
  property_value: number | null;
  monthly_income: number | null;
}): ComplianceCheckResult {
  const warnings: ComplianceCheckResult["warnings"] = [];
  const amount = Number(lead.mortgage_amount) || 0;
  const property = Number(lead.property_value) || 0;
  const income = Number(lead.monthly_income) || 0;

  // LTV check — Bank of Israel max 75% for primary residence
  if (property > 0 && amount > 0) {
    const ltv = (amount / property) * 100;
    if (ltv > 75) {
      warnings.push({
        code: "LTV_EXCEED",
        label: "חריגת LTV",
        value: `${ltv.toFixed(1)}%`,
        limit: "75%",
        severity: ltv > 90 ? "error" : "warning",
      });
    }
  }

  // DTI check — max 40% of gross income
  if (income > 0 && amount > 0) {
    const monthlyPayment = amount / 240; // rough 20yr estimate
    const dti = (monthlyPayment / income) * 100;
    if (dti > 40) {
      warnings.push({
        code: "DTI_EXCEED",
        label: "חריגת יחס החזר",
        value: `${dti.toFixed(1)}%`,
        limit: "40%",
        severity: dti > 50 ? "error" : "warning",
      });
    }
  }

  // Equity check — minimum 25%
  if (property > 0 && amount > 0) {
    const equity = ((property - amount) / property) * 100;
    if (equity < 25) {
      warnings.push({
        code: "LOW_EQUITY",
        label: "הון עצמי נמוך",
        value: `${equity.toFixed(1)}%`,
        limit: "25%",
        severity: equity < 15 ? "error" : "warning",
      });
    }
  }

  return { passed: warnings.length === 0, warnings };
}

/* Visual compliance warnings banner */
export function ComplianceGuardrail({ lead }: {
  lead: { mortgage_amount: number | null; property_value: number | null; monthly_income: number | null };
}) {
  const result = useMemo(() => runComplianceCheck(lead), [lead]);

  if (result.passed) {
    return (
      <div className="flex items-center gap-2 p-3 rounded-lg bg-emerald-500/5 border border-emerald-500/20 text-xs">
        <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
        <span className="text-emerald-400 font-semibold">עובר בדיקת ציות רגולטורי — אין חריגות</span>
      </div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: -8 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl border border-destructive/30 bg-destructive/5 overflow-hidden"
    >
      <div className="flex items-center gap-2 p-3 border-b border-destructive/20">
        <div className="p-1.5 rounded-lg bg-destructive/10">
          <AlertTriangle className="w-4 h-4 text-destructive" />
        </div>
        <span className="text-sm font-bold text-destructive">
          חריגה רגולטורית: התיק עלול להידחות על הסף
        </span>
      </div>
      <div className="p-3 space-y-2">
        {result.warnings.map((w) => (
          <div
            key={w.code}
            className={cn(
              "flex items-center justify-between p-2 rounded-lg text-xs",
              w.severity === "error"
                ? "bg-destructive/10 border border-destructive/20"
                : "bg-amber-500/10 border border-amber-500/20"
            )}
          >
            <div className="flex items-center gap-2">
              <XCircle className={cn("w-3.5 h-3.5", w.severity === "error" ? "text-destructive" : "text-amber-400")} />
              <span className={cn("font-semibold", w.severity === "error" ? "text-destructive" : "text-amber-400")}>
                {w.label}
              </span>
            </div>
            <div className="flex items-center gap-3 text-muted-foreground">
              <span>ערך: <strong className="text-foreground">{w.value}</strong></span>
              <span>מותר: <strong className="text-foreground">{w.limit}</strong></span>
            </div>
          </div>
        ))}
      </div>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────────────────────
   3. AUDIT LOG — per-case "Black Box" timeline
   ───────────────────────────────────────────────────────────── */
interface AuditEntry {
  id: string;
  timestamp: string;
  action: string;
  detail: string;
  policyVersion?: string;
  actor: "system" | "user" | "ai";
}

function generateAuditEntries(lead: {
  id: string;
  full_name: string;
  status: string;
  created_at: string;
  mortgage_amount: number | null;
  property_value: number | null;
  monthly_income: number | null;
}): AuditEntry[] {
  const entries: AuditEntry[] = [];
  const created = new Date(lead.created_at);

  entries.push({
    id: `${lead.id}-1`,
    timestamp: created.toISOString(),
    action: "תיק נפתח",
    detail: `נוצר תיק עבור ${lead.full_name}`,
    actor: "user",
  });

  if (lead.mortgage_amount) {
    const t = new Date(created.getTime() + 60000);
    entries.push({
      id: `${lead.id}-2`,
      timestamp: t.toISOString(),
      action: "נתונים פיננסיים הוזנו",
      detail: `סכום משכנתא: ₪${Number(lead.mortgage_amount).toLocaleString()}`,
      actor: "user",
    });
  }

  // AI analysis
  const aiTime = new Date(created.getTime() + 120000);
  entries.push({
    id: `${lead.id}-3`,
    timestamp: aiTime.toISOString(),
    action: "ניתוח AI בוצע",
    detail: "סריקת חיתום אוטומטית — מדיניות אשראי v2.4",
    policyVersion: "BOI Credit Policy v2.4 (03/2026)",
    actor: "ai",
  });

  if (lead.property_value && lead.mortgage_amount) {
    const ltv = ((Number(lead.mortgage_amount) / Number(lead.property_value)) * 100).toFixed(1);
    entries.push({
      id: `${lead.id}-4`,
      timestamp: new Date(aiTime.getTime() + 30000).toISOString(),
      action: "בדיקת LTV",
      detail: `יחס LTV: ${ltv}% — ${Number(ltv) <= 75 ? "תקין" : "חריגה"}`,
      policyVersion: "BOI Directive 329 (LTV Limits)",
      actor: "ai",
    });
  }

  if (["submitted", "approved", "closed"].includes(lead.status)) {
    entries.push({
      id: `${lead.id}-5`,
      timestamp: new Date(aiTime.getTime() + 300000).toISOString(),
      action: "דוח חיתום הופק",
      detail: "Executive Dossier PDF נוצר ואומת",
      policyVersion: "Chitumit Underwriting Engine v2.0",
      actor: "system",
    });
  }

  if (lead.status === "approved") {
    entries.push({
      id: `${lead.id}-6`,
      timestamp: new Date(aiTime.getTime() + 600000).toISOString(),
      action: "אישור התקבל",
      detail: "התיק אושר — צילום מצב נשמר",
      actor: "system",
    });
  }

  return entries.sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime());
}

const actorConfig = {
  system: { label: "מערכת", color: "text-primary", icon: Lock },
  user: { label: "משתמש", color: "text-gold", icon: FileText },
  ai: { label: "AI", color: "text-emerald-400", icon: ShieldCheck },
};

export function AuditLog({ lead }: {
  lead: {
    id: string;
    full_name: string;
    status: string;
    created_at: string;
    mortgage_amount: number | null;
    property_value: number | null;
    monthly_income: number | null;
  };
}) {
  const [expanded, setExpanded] = useState(false);
  const entries = useMemo(() => generateAuditEntries(lead), [lead]);

  return (
    <div className="rounded-xl border border-border/30 bg-card overflow-hidden">
      <button
        onClick={() => setExpanded(!expanded)}
        className="w-full flex items-center justify-between p-4 hover:bg-muted/30 transition-colors"
      >
        <div className="flex items-center gap-2">
          <div className="p-1.5 rounded-lg bg-gold/10 border border-gold/20">
            <Fingerprint className="w-4 h-4 text-gold" />
          </div>
          <div className="text-right">
            <p className="text-sm font-bold text-foreground">יומן חיתום משפטי</p>
            <p className="text-[10px] text-muted-foreground">Audit Trail — {entries.length} רשומות</p>
          </div>
        </div>
        {expanded ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}
      </button>

      <AnimatePresence>
        {expanded && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="px-4 pb-4 space-y-2 max-h-[300px] overflow-y-auto">
              {entries.map((entry) => {
                const actor = actorConfig[entry.actor];
                const ActorIcon = actor.icon;
                return (
                  <div
                    key={entry.id}
                    className="flex items-start gap-3 p-2.5 rounded-lg bg-secondary/20 border border-border/20"
                  >
                    <div className={cn("p-1 rounded-md mt-0.5 shrink-0 bg-secondary/60")}>
                      <ActorIcon className={cn("w-3 h-3", actor.color)} />
                    </div>
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center justify-between">
                        <span className="text-xs font-semibold text-foreground">{entry.action}</span>
                        <span className="text-[9px] text-muted-foreground flex items-center gap-1">
                          <Clock className="w-2.5 h-2.5" />
                          {new Date(entry.timestamp).toLocaleString("he-IL", {
                            day: "2-digit", month: "2-digit", year: "2-digit",
                            hour: "2-digit", minute: "2-digit",
                          })}
                        </span>
                      </div>
                      <p className="text-[10px] text-muted-foreground mt-0.5">{entry.detail}</p>
                      {entry.policyVersion && (
                        <div className="flex items-center gap-1 mt-1 text-[9px] text-gold/70">
                          <Eye className="w-2.5 h-2.5" />
                          <span>גרסת מדיניות: {entry.policyVersion}</span>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
            <div className="px-4 pb-3">
              <div className="p-2 rounded-lg bg-gold/5 border border-gold/10">
                <p className="text-[9px] text-gold/70 flex items-center gap-1.5">
                  <Lock className="w-3 h-3 shrink-0" />
                  <span>הרשומות מוצפנות ולא ניתנות לעריכה. בכל רגע נתון, ליועץ יש הוכחה שהתיק עמד בדרישות.</span>
                </p>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/* ─────────────────────────────────────────────────────────────
   4. CLIENT TERMS ACCEPTANCE GATE
   ───────────────────────────────────────────────────────────── */
export function ClientTermsGate({
  accepted,
  onAccept,
}: {
  accepted: boolean;
  onAccept: () => void;
}) {
  if (accepted) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      className="rounded-xl border border-gold/20 bg-gradient-to-b from-gold/5 to-transparent p-5 space-y-4"
    >
      <div className="flex items-center gap-2">
        <div className="p-1.5 rounded-lg bg-gold/10 border border-gold/20">
          <ShieldCheck className="w-5 h-5 text-gold" />
        </div>
        <h3 className="text-sm font-bold text-foreground">הצהרת אחריות ותנאי שימוש</h3>
      </div>

      <div className="p-4 rounded-lg bg-secondary/30 border border-border/20 text-xs text-muted-foreground space-y-2 max-h-[180px] overflow-y-auto" dir="rtl">
        <p className="font-semibold text-foreground">הצהרת לקוח בדבר דיוק הנתונים</p>
        <p>
          אני מצהיר/ה כי כל הנתונים והמסמכים שאני מעלה למערכת חיתומית הם מדויקים, עדכניים ולא עברו שינוי
          מכל סוג. ידוע לי שהניתוח מבוסס על הנתונים שאני מזין/ה, והמערכת אינה אחראית לאי-דיוקים בנתוני המקור.
        </p>
        <p>
          אני מאשר/ת כי קראתי את{" "}
          <a href="/terms" className="text-gold underline" target="_blank" rel="noopener noreferrer">
            תנאי השימוש
          </a>
          {" "}ואת{" "}
          <a href="/privacy" className="text-gold underline" target="_blank" rel="noopener noreferrer">
            מדיניות הפרטיות
          </a>
          {" "}והנני מסכים/ה להם.
        </p>
        <p>
          ידוע לי שדוח החיתום מהווה אינדיקציה טכנולוגית בלבד ואינו מהווה אישור סופי של בנק או מוסד פיננסי.
          האחריות על ההחלטה הסופית בנוגע לנטילת משכנתא חלה עליי בלבד.
        </p>
      </div>

      <button
        onClick={onAccept}
        className="w-full flex items-center justify-center gap-2 py-3 px-4 rounded-lg bg-gold text-background font-bold text-sm hover:bg-gold/90 transition-colors"
      >
        <CheckCircle2 className="w-4 h-4" />
        אני מאשר/ת — הנתונים מדויקים ותנאי השימוש מקובלים עליי
      </button>

      <p className="text-[9px] text-muted-foreground text-center">
        ללא אישור תנאים אלו, לא ניתן להעלות מסמכים או להפיק דוחות.
      </p>
    </motion.div>
  );
}

/* ─────────────────────────────────────────────────────────────
   5. PDF HELPERS — add disclaimer + watermark to jsPDF docs
   ───────────────────────────────────────────────────────────── */
import jsPDF from "jspdf";

/**
 * Adds legal disclaimer footer to every page of a jsPDF doc.
 * Call AFTER all content pages have been created.
 */
export function addDisclaimerToAllPages(doc: jsPDF) {
  const rtl = (text: string) => text.split("").reverse().join("");
  const totalPages = doc.getNumberOfPages();

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    // Separator line
    doc.setDrawColor(100, 100, 100);
    doc.setLineWidth(0.3);
    doc.line(15, pageHeight - 22, pageWidth - 15, pageHeight - 22);

    // Disclaimer text
    doc.setFontSize(5.5);
    doc.setTextColor(120, 120, 120);

    const disclaimerLines = doc.splitTextToSize(rtl(LEGAL_DISCLAIMER_HE), pageWidth - 40);
    disclaimerLines.forEach((line: string, idx: number) => {
      doc.text(line, pageWidth / 2, pageHeight - 18 + idx * 3, { align: "center" });
    });

    // Watermark hash
    doc.setFontSize(4.5);
    doc.setTextColor(80, 80, 80);
    const hash = `Chitumit-Verified | SHA: ${generateDocHash(doc, i)} | Page ${i}/${totalPages}`;
    doc.text(hash, pageWidth / 2, pageHeight - 5, { align: "center" });
  }
}

/**
 * Adds diagonal watermark on the current page
 */
export function addSecureWatermark(doc: jsPDF, text = "CHITUMIT VERIFIED") {
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  doc.saveGraphicsState();
  // @ts-ignore — jsPDF GState
  doc.setGState(new (doc as any).GState({ opacity: 0.04 }));
  doc.setFontSize(60);
  doc.setTextColor(212, 175, 55);

  // Rotate and center
  const centerX = pageWidth / 2;
  const centerY = pageHeight / 2;
  doc.text(text, centerX, centerY, {
    align: "center",
    angle: 35,
  });
  doc.restoreGraphicsState();
}

function generateDocHash(_doc: jsPDF, page: number): string {
  const ts = Date.now().toString(36);
  const pg = page.toString(16).padStart(2, "0");
  return `${ts.slice(-6)}${pg}`.toUpperCase();
}
